In [ ]:
import gym
import gym.envs.toy_text.frozen_lake as fl
import numpy as np

env = gym.make('FrozenLake-v0',is_slippery=False)
env.render()


SFFF
FHFH
FFFH
HFFG


In [ ]:
nbStates = env.observation_space.n 
nbActions = env.action_space.n

In [ ]:
V = np.zeros(nbStates)
V

array([0., 0., 0., 0.])

In [ ]:
V = np.zeros(nbStates)
gamma = 0.9

for i in range(21):
  V_i = np.zeros(nbStates)
  for s in range(nbStates-1):
    q_vals = np.zeros(nbActions)
    for a in range(nbActions):                                           # iterate for every action              
      #print("s=",s,"a=",a)
      q_a = 0
      ## What are the outcomes of action 'a' in state 's'
      outcomes = env.unwrapped.P[s][a] 
      for o in outcomes:
        transition_prob = o[0]
        s_prime = o[1]
        reward = o[2]
        q_a += transition_prob * (reward + gamma * V[s_prime])
      q_vals[a] = q_a
    V_i[s] = q_vals[np.argmax(q_vals) ]
  V=V_i 
 
print(V)

[0.59049 0.6561  0.729   0.6561  0.6561  0.      0.81    0.      0.729
 0.81    0.9     0.      0.      0.9     1.      0.     ]


In [ ]:
np.reshape(V,(4,4))

array([[0.59049, 0.6561 , 0.729  , 0.6561 ],
       [0.6561 , 0.     , 0.81   , 0.     ],
       [0.729  , 0.81   , 0.9    , 0.     ],
       [0.     , 0.9    , 1.     , 0.     ]])

In [ ]:
# Find optimal policy
pi = np.zeros(nbStates)
for s in range(nbStates-1):
    q_vals = np.zeros(nbActions)
    for a in range(nbActions):                                           # iterate for every action              
      #print("s=",s,"a=",a)
      q_a = 0
      outcomes = env.unwrapped.P[s][a] 
      for o in outcomes:
        transition_prob = o[0]
        s_prime = o[1]
        reward = o[2]
        q_a += transition_prob * (reward + gamma * V[s_prime])
      q_vals[a] = q_a
      
    pi[s] = np.argmax(q_vals)
    #print("s=",s,",q_vals:",q_vals,"pi[s]:",pi[s])

print(pi)

[1. 2. 1. 0. 1. 0. 1. 0. 2. 1. 1. 0. 0. 2. 2. 0.]


In [ ]:
## Follow policy
env.reset()
s=0
for t in range(10):
  a = pi[s]
  print("s=",s,"a=",a)
  s_prime, reward, done, info = env.step(a)
  #print(s_prime)
  if done==True:
       break
  else:
    s=s_prime

s= 0 a= 1.0
s= 4 a= 1.0
s= 8 a= 2.0
s= 9 a= 1.0
s= 13 a= 2.0
s= 14 a= 2.0
